### ISSUE TITLE
Propuestas de logo

### ISSUE THREAD

**Issue by ferdinandalexa** [midudev/curso-nextjs-twitter-clone#2]
¡Hola, @midudev!  
Pude rascar algo de tiempo entre semana para preparar unas propuestas para "devter".

Ya sea que te decidas por uno o lo pongas a votación de la comunidad. Ya prepararía los archivos necesarios para el proyecto y haría el pull request correspondiente.

![Instagram__Crecimiento](https://user-images.githubusercontent.com/37825362/89485798-2e808780-d767-11ea-8b72-15836a7b31d6.png)
![Instagram__Simbolico-01](https://user-images.githubusercontent.com/37825362/89485801-2f191e00-d767-11ea-931b-650518577bdb.png)
![Instagram__Simbolico-02](https://user-images.githubusercontent.com/37825362/89485803-2fb1b480-d767-11ea-8e00-eab6f1c9dba2.png)

**Comment by midudev** [comment]
Me encanta el búho! jajaja He puesto una encuesta aquí, a ver si la gente se anima a votar:
https://www.youtube.com/post/UgzWriYtiuHjYM0cehN4AaABCQ

**Comment by midudev** [comment]
:) Al final añadimos el mochuelo!
